version: '3.8'
services:
  db:
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=edunote
    networks:
      - edunote
networks:
  edunote: